/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasFileManagerWindow: typeof import('./src/components/canvas/CanvasFileManagerWindow.vue')['default']
    CanvasPluginWindow: typeof import('./src/components/canvas/CanvasPluginWindow.vue')['default']
    CanvasPreviewWindow: typeof import('./src/components/canvas/CanvasPreviewWindow.vue')['default']
    CanvasWindow: typeof import('./src/components/canvas/CanvasWindow.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FileToolbar: typeof import('./src/components/FileToolbar.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    JobTable: typeof import('./src/components/JobTable.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    MoleculeViewer: typeof import('./src/components/MoleculeViewer.vue')['default']
    MonacoTextEditor: typeof import('./src/components/MonacoTextEditor.vue')['default']
    QueueStatus: typeof import('./src/components/QueueStatus.vue')['default']
    TerminalPanel: typeof import('./src/components/terminal/TerminalPanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
